[project]
name = "kaggle"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.4.1",
    "torchvision>=0.19.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
